version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init_postgis.sh:/docker-entrypoint-initdb.d/init_postgis.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d yourdatabase"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/yourdatabase
      SPRING_DATASOURCE_USERNAME: youruser
      SPRING_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8443:8443"

volumes:
  postgres-data:
